version: '3'
services:
  app:
    environment:
      - PROJECT_ID
      - VERSION
    image: gcr.io/${PROJECT_ID}/hello-app:${VERSION}
    tty: true
    build:
      context: .
      args: 
        APP_NAME: $APP_NAME
        WORKDIR: $WORKDIR
        PORT: $PORT
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:${WORKDIR}