version: '3'
services:
  app:
    tty: true
    build:
      context: .
      args: 
        APP_NAME: $APP_NAME
        WORKDIR: $WORKDIR
        PORT: $PORT
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:${WORKDIR}