version: '3'
services:
  app:
    tty: true
    build:
      context: .
      args: 
        APP_NAME: $APP_NAME
        WORKDIR: $WORKDIR
        PORT: $APP_PORT
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - db
    volumes:
      - .:${WORKDIR}

  db:
    image: postgres:13-alpine
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - "./data/db:/var/lib/postgresql/data"
      - ./data/db/init:/docker-entrypoint-initdb.d